baseURL = "https://www.kipuai.com/"
languageCode = "en-us"
title = "Kipu"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id = ""

[params.logo]
  name = "Kipu"
  mobile = "images/favicon.png"
  mobile_height = "36px"
  mobile_width = "36px"
  desktop = "images/kipumain.png"     # <-- ✅ This must match exactly
  desktop_height = "29px"
  desktop_width = ""
  alt = "Kipu"

[params.homepage_meta_tags]
    meta_description = "Kipu is your partner to unlock your data & AI potential, and deliver measurable outcomes."
    meta_og_title = "Kipu"
    meta_og_type = "website"
    meta_og_url = "https://kipuai.com"
    meta_og_image = "images/meta_og_image.png"
    meta_og_description = "Kipu is your partner to unlock your data & AI potential, and deliver measurable outcomes."
    meta_twitter_card = "summary"
    meta_twitter_site = "@kipuai"
    meta_twitter_creator = "@kipuai"

[params.hero]
  heading = "Unlock Your Data & AI Potential"
  subheading = "Expert guidance to make your data and AI initiatives deliver measurable outcomes"
  background = "images/officecollab.png"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
